[Photon_ESP32_C6]
extends = esp32c6_base
board = seeed_xiao_esp32c6
board_build.partitions = min_spiffs.csv ; get around 4mb flash limit
build_flags =
  ${esp32c6_base.build_flags}
  -I variants/photon_esp32_c6
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1
  -D PHOTON_ESP32_C6
  -D USE_SX1262
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D LORA_TX_POWER=22
  -D P_LORA_TX_LED=LED_BUILTIN
  -D P_LORA_SCLK=D8
  -D P_LORA_MISO=D9
  -D P_LORA_MOSI=D10
  -D P_LORA_NSS=D4
  -D P_LORA_DIO_1=D1
  -D P_LORA_BUSY=D3
  -D P_LORA_RESET=D2
  -D PIN_BOARD_SCL=D6
  -D PIN_BOARD_SDA=D7
  -D SX126X_RXEN=D5
  -D SX126X_DIO2_AS_RF_SWITCH=true
  -D SX126X_DIO3_TCXO_VOLTAGE=1.8
  -D SX126X_CURRENT_LIMIT=140
  -D SX126X_RX_BOOSTED_GAIN=1
  -D DISABLE_WIFI_OTA=1
build_src_filter = ${esp32c6_base.build_src_filter}
  +<../variants/photon_esp32_c6>
  +<PhotonESP32C6Board.cpp>
lib_deps =
  ${esp32c6_base.lib_deps}

[env:photon_esp32_c6_kiss_tcp_modem]
extends = Photon_ESP32_C6
build_flags =
  ${Photon_ESP32_C6.build_flags}
  -D ENABLE_KISS_TCP=1
  -D KISS_TCP_PORT=8001
  -D KISS_WIFI_SSID='"Photon-C6-KISS"'
build_src_filter = ${Photon_ESP32_C6.build_src_filter}
  +<../examples/kiss_modem/*.cpp>
lib_deps =
  ${Photon_ESP32_C6.lib_deps}
