[meshsmith_photon]
extends = nrf52_base
board = seeed-xiao-afruitnrf52-nrf52840
board_build.ldscript = boards/nrf52840_s140_v7.ld
build_flags = ${nrf52_base.build_flags}
  ${sensor_base.build_flags}
  -D NRF52_PLATFORM -D XIAO_NRF52
  -I lib/nrf52/s140_nrf52_7.3.0_API/include
  -I lib/nrf52/s140_nrf52_7.3.0_API/include/nrf52
  -I variants/meshsmith_photon
  -I src/helpers/nrf52
  -D P_LORA_TX_LED=11
  -D DISPLAY_CLASS=NullDisplayDriver
   -D USE_SX1262
   -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D P_LORA_DIO_1=D0
  -D P_LORA_RESET=D1
  -D P_LORA_BUSY=D2
  -D P_LORA_NSS=D3
  -D SX126X_RXEN=RADIOLIB_NC
  -D SX126X_TXEN=RADIOLIB_NC
  -D SX126X_DIO2_AS_RF_SWITCH=1
  -D SX126X_DIO3_TCXO_VOLTAGE=1.8
  -D SX126X_CURRENT_LIMIT=140
  -D SX126X_RX_BOOSTED_GAIN=1
  -D PIN_WIRE_SCL=5
  -D PIN_WIRE_SDA=4
  -D PIN_GPS_TX=PIN_SERIAL1_RX
  -D PIN_GPS_RX=PIN_SERIAL1_TX
  -D GPS_BAUD_RATE=115200
  -D PHOTON_HAS_BATT_CHARGE_RATE=1
lib_deps = ${nrf52_base.lib_deps}
  ${sensor_base.lib_deps}



[meshsmith_photon_e22p_30dbm]
extends = meshsmith_photon
; limit txpower to 20dBm on E22-900M30S. Anything higher will
; cause distortion in the PA output. 20dBm in -> 30dBm out
build_flags =
  ${meshsmith_photon.build_flags}
  -D MANUFACTURER_STRING='"Meshsmith Photon-E22P-30dBm (Xiao_nrf52)"'
  -D LORA_TX_POWER=20
build_src_filter = ${meshsmith_photon.build_src_filter}
  +<helpers/*.cpp>
  +<helpers/sensors>
  +<helpers/ui/NullDisplayDriver.cpp>
  +<../variants/meshsmith_photon>


;;; abstracted firmware roles

[meshsmith_photon_companion_radio_ble]
extends = meshsmith_photon
board_build.ldscript = boards/nrf52840_s140_v7_extrafs.ld
board_upload.maximum_size = 708608
build_flags =
  ${meshsmith_photon.build_flags}
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D BLE_PIN_CODE=123456
  -D OFFLINE_QUEUE_SIZE=256
  -I examples/companion_radio/ui-new
  -D QSPIFLASH=1
;  -D BLE_DEBUG_LOGGING=1
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${meshsmith_photon.build_src_filter}
  +<helpers/nrf52/SerialBLEInterface.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps =
  ${meshsmith_photon.lib_deps}
  densaugeo/base64 @ ~1.4.0

[meshsmith_photon_repeater]
extends = meshsmith_photon
build_flags =
  ${meshsmith_photon.build_flags}
  -D ADVERT_NAME='"Meshsmith Photon Repeater"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
  -D MESHSMITH_PHOTON_GPS_TIME=1
  -D MESHSMITH_PHOTON_LOW_ACTIVITY_GPS=1
  -D GPS_SERIAL_SUSPEND_WHEN_STOPPED=1
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${meshsmith_photon.build_src_filter}
  +<helpers/ui/NullDisplayDriver.cpp>
  +<../examples/simple_repeater/*.cpp>


;Meshsmith
[env:meshsmith_photon_e22p_30dbm_companion_radio_ble]
extends =
   meshsmith_photon_e22p_30dbm
   meshsmith_photon_companion_radio_ble
build_flags =
   ${meshsmith_photon_companion_radio_ble.build_flags}
   ${meshsmith_photon_e22p_30dbm.build_flags}
build_src_filter =
   ${meshsmith_photon_companion_radio_ble.build_src_filter}
   ${meshsmith_photon_e22p_30dbm.build_src_filter}

[env:meshsmith_photon_e22p_30dbm_repeater]
extends =
   meshsmith_photon_e22p_30dbm
   meshsmith_photon_repeater
build_flags =
   ${meshsmith_photon_repeater.build_flags}
   ${meshsmith_photon_e22p_30dbm.build_flags}
build_src_filter =
   ${meshsmith_photon_repeater.build_src_filter}
   ${meshsmith_photon_e22p_30dbm.build_src_filter}
